# If set to false it only displays the messages and doesn't add or subtract anything
useVault: false
discord:
  webhookURL: "https://discord.com/api/webhooks/1268600822867165325/JSuVk9bg0j7Ksm1Z9H78ib4f1XfK9qXXtMMzl1kgifnMqrxy1h3EXN6qgCOhJ835TJx2"
  iconURL: ""
  # As hexadecimal color code
  color: "#5fc0d4"
